# Generated by Django 2.2.5 on 2019-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep', models.CharField(max_length=100)),
                ('D1P1', models.CharField(max_length=100)),
                ('D1P2', models.CharField(max_length=100)),
                ('D1P3', models.CharField(max_length=100)),
                ('D1P4', models.CharField(max_length=100)),
                ('D1P5', models.CharField(max_length=100)),
                ('D1P6', models.CharField(max_length=100)),
                ('D1P7', models.CharField(max_length=100)),
            ],
        ),
    ]
