# Generated by Django 2.2.5 on 2019-11-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_debtt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebTT',
            new_name='Deptt',
        ),
    ]
