# Generated by Django 2.2.5 on 2019-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191102_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep', models.CharField(max_length=100)),
                ('D1P1', models.CharField(max_length=100)),
                ('D1P2', models.CharField(max_length=100)),
                ('D1P3', models.CharField(max_length=100)),
                ('D1P4', models.CharField(max_length=100)),
                ('D1P5', models.CharField(max_length=100)),
                ('D1P6', models.CharField(max_length=100)),
                ('D1P7', models.CharField(max_length=100)),
                ('D2P1', models.CharField(max_length=100)),
                ('D2P2', models.CharField(max_length=100)),
                ('D2P3', models.CharField(max_length=100)),
                ('D2P4', models.CharField(max_length=100)),
                ('D2P5', models.CharField(max_length=100)),
                ('D2P6', models.CharField(max_length=100)),
                ('D2P7', models.CharField(max_length=100)),
                ('D3P1', models.CharField(max_length=100)),
                ('D3P2', models.CharField(max_length=100)),
                ('D3P3', models.CharField(max_length=100)),
                ('D3P4', models.CharField(max_length=100)),
                ('D3P5', models.CharField(max_length=100)),
                ('D3P6', models.CharField(max_length=100)),
                ('D3P7', models.CharField(max_length=100)),
                ('D4P1', models.CharField(max_length=100)),
                ('D4P2', models.CharField(max_length=100)),
                ('D4P3', models.CharField(max_length=100)),
                ('D4P4', models.CharField(max_length=100)),
                ('D4P5', models.CharField(max_length=100)),
                ('D4P6', models.CharField(max_length=100)),
                ('D4P7', models.CharField(max_length=100)),
                ('D5P1', models.CharField(max_length=100)),
                ('D5P2', models.CharField(max_length=100)),
                ('D5P3', models.CharField(max_length=100)),
                ('D5P4', models.CharField(max_length=100)),
                ('D5P5', models.CharField(max_length=100)),
                ('D5P6', models.CharField(max_length=100)),
                ('D5P7', models.CharField(max_length=100)),
                ('D6P1', models.CharField(max_length=100)),
                ('D6P2', models.CharField(max_length=100)),
                ('D6P3', models.CharField(max_length=100)),
                ('D6P4', models.CharField(max_length=100)),
                ('D6P5', models.CharField(max_length=100)),
                ('D6P6', models.CharField(max_length=100)),
                ('D6P7', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Deptt',
        ),
    ]
