# Generated by Django 2.2.5 on 2020-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191108_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Roll_No',
            field=models.IntegerField(),
        ),
    ]
